package com.voidboost.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.narration.NarrationElementOutput;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.network.chat.Component;

/** Lightweight premium configuration UI. */
public final class VoidBoostScreen extends Screen {
    private static final int BG=0xFF07090E,SHELL=0xFF0B0F17,SIDE=0xFF090C13,CARD=0xFF101621,HOVER=0xFF171F2C,SEL=0xFF19182A,BORDER=0xFF222B39,ACCENT=0xFF9B7CFF,SOFT=0xFF2A2148,TEXT=0xFFF5F6FA,MUTED=0xFF7F8A9F,GOOD=0xFF75E0A4,BAD=0xFFE07B8B;
    private final Screen parent;
    private int page;
    private double scroll;

    public VoidBoostScreen(Screen parent){super(Component.literal("VoidBoost"));this.parent=parent;}
    @Override protected void init(){rebuildWidgets();}
    @Override protected void rebuildWidgets(){
        clearWidgets(); int sx=26,cx=202,r=width-26,y=122-(int)scroll;
        nav(sx+10,116,"General",0); nav(sx+10,158,"Visual",1); nav(sx+10,200,"Performance",2); nav(sx+10,242,"Advanced",3);
        if(page==0) general(cx,r,y); else if(page==1) visual(cx,r,y); else if(page==2) performance(cx,r,y); else advanced(cx,r,y);
        button(sx+10,height-70,72,40,"Reset","",()->{scroll=0;VoidBoostConfig.applyBalancedPreset();rebuildWidgets();},false,true,"Restore Balanced");
        button(r-112,height-70,112,40,"Done","SAVE",()->{VoidBoostConfig.save();Minecraft.getInstance().setScreen(parent);},true,true,"Save and close");
    }
    private int maxScroll(){return switch(page){case 0->250;case 1->170;case 2->170;default->230;};}
    @Override public boolean mouseScrolled(double mx,double my,double sx,double sy){if(mx<190||my<82||my>height-78)return super.mouseScrolled(mx,my,sx,sy);double old=scroll;scroll=Math.max(0,Math.min(maxScroll(),scroll-sy*42));if(old!=scroll)rebuildWidgets();return true;}
    private void nav(int x,int y,String n,int p){button(x,y,134,34,n,p==page?"●":"",()->{page=p;scroll=0;rebuildWidgets();},p==page,true,"");}
    private void general(int l,int r,int y){int w=(r-l-14)/2;button(l,y+18,w,82,"Balanced","STABLE",VoidBoostConfig::applyBalancedPreset,preset("balanced"),false,"Smooth visuals • reliable FPS");button(l+w+14,y+18,w,82,"Competitive","PVP",VoidBoostConfig::applyCompetitivePreset,preset("competitive"),false,"Low latency • PvP rendering");button(l,y+114,w,82,"MAX FPS","FAST",VoidBoostConfig::applyMaxFpsPreset,preset("max"),false,"Aggressive optimization");button(l+w+14,y+114,w,82,"ULTIMATE FPS","EXTREME",VoidBoostConfig::applyUltimateLockedPreset,preset("ultimate"),false,"Maximum performance cuts");button(l,y+210,r-l,62,"Custom","MANUAL",this::custom,preset("custom"),false,"Tune every control yourself");setting(l,y+290,r,"Dynamic Render Distance",state("dynamic"),"Adaptive chunks",()->toggle("dynamic"));setting(l,y+342,r,"Target FPS",VoidBoostConfig.get().dynamicTargetFps+" FPS","Adaptive target",this::target);setting(l,y+394,r,"Performance Mode",state("performance"),"Optimized vanilla settings",()->toggle("performance"));}
    private void visual(int l,int r,int y){setting(l,y+20,r,"Particles",state("particles"),"ALL / REDUCED / MINIMAL",()->toggle("particles"));setting(l,y+72,r,"Entity Shadows",state("shadows"),"Entity shadow pass",()->toggle("shadows"));setting(l,y+124,r,"Weather Effects",state("weather"),"Weather render radius",()->toggle("weather"));setting(l,y+176,r,"Cloud Optimization",state("clouds"),"Disable cloud rendering",()->toggle("clouds"));setting(l,y+228,r,"Animation Optimization",state("animations"),"Reduce animation workload",()->toggle("animations"));setting(l,y+280,r,"Fog Optimization",state("fog"),"Reduce fog work",()->toggle("fog"));setting(l,y+332,r,"Vignette Optimization",state("vignette"),"Disable vignette pass",()->toggle("vignette"));setting(l,y+384,r,"Ambient Occlusion",state("ao"),"Disable AO shading",()->toggle("ao"));}
    private void performance(int l,int r,int y){setting(l,y+20,r,"Entity Optimization",state("entities"),"Cull distant entities",()->toggle("entities"));setting(l,y+72,r,"Entity Distance",VoidBoostConfig.get().maxEntityDistance+" BLOCKS","Maximum entity distance",this::entityDistance);setting(l,y+124,r,"Render Distance",VoidBoostConfig.get().maxRenderDistance+" CHUNKS","Maximum chunk distance",this::renderDistance);setting(l,y+176,r,"Dynamic Render Distance",state("dynamic"),"React to FPS",()->toggle("dynamic"));setting(l,y+228,r,"Performance Monitor",state("monitor"),"Low-overhead diagnostics",()->toggle("monitor"));setting(l,y+280,r,"View Bobbing",state("viewbob"),"Disable camera bob",()->toggle("viewbob"));setting(l,y+332,r,"FPS Limit",VoidBoostConfig.get().targetFps+" FPS","Client frame limit",this::fpsLimit);}
    private void advanced(int l,int r,int y){setting(l,y+20,r,"Mipmap Optimization",state("mipmap"),"Zero mipmap levels",()->toggle("mipmap"));setting(l,y+72,r,"Biome Blend Optimization",state("biome"),"Disable biome blending",()->toggle("biome"));setting(l,y+124,r,"VSync Optimization",state("vsync"),"Disable frame synchronization",()->toggle("vsync"));setting(l,y+176,r,"Particle Budget",VoidBoostConfig.get().particleLimitPercent+"%","Reduced-particle sampling budget",this::particleBudget);addInfo(l,y+238,r,"LIGHTWEIGHT ENGINE");addInfo(l,y+286,r,mode()+" • LOCAL CONFIG");}
    private void setting(int l,int y,int r,String t,String v,String d,Runnable a){button(l,y,r-l,44,t,v,a,false,false,d);}
    private void addInfo(int l,int y,int r,String t){button(l,y,r-l,40,t,"ACTIVE",()->{},true,false,"");}
    private void button(int x,int y,int w,int h,String t,String v,Runnable a,boolean s,boolean c,String d){addRenderableWidget(new PremiumButton(x,y,w,h,t,v,d,a,s,c));}
    private void custom(){VoidBoostConfig c=VoidBoostConfig.get();c.maxFpsPreset=false;c.competitiveMode=false;c.ultimateLocked=false;c.markDirty();rebuildWidgets();}
    private void toggle(String k){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked&&!k.equals("performance"))return;switch(k){case"particles"-> {if(c.disableParticles){c.disableParticles=false;c.reducedParticles=true;}else if(c.reducedParticles)c.reducedParticles=false;else c.disableParticles=true;}case"dynamic"->c.dynamicRenderDistance=!c.dynamicRenderDistance;case"entities"->c.entityRenderOptimization=!c.entityRenderOptimization;case"shadows"->c.entityShadows=!c.entityShadows;case"weather"->c.weatherEffects=!c.weatherEffects;case"clouds"->c.cloudOptimization=!c.cloudOptimization;case"animations"->c.animationOptimization=!c.animationOptimization;case"fog"->c.fogOptimization=!c.fogOptimization;case"vignette"->c.vignetteOptimization=!c.vignetteOptimization;case"ao"->c.ambientOcclusionOptimization=!c.ambientOcclusionOptimization;case"mipmap"->c.mipmapOptimization=!c.mipmapOptimization;case"biome"->c.biomeBlendOptimization=!c.biomeBlendOptimization;case"vsync"->c.vsyncOptimization=!c.vsyncOptimization;case"viewbob"->c.viewBobOptimization=!c.viewBobOptimization;case"performance"->{c.performanceMode=!c.performanceMode;if(!c.performanceMode)c.ultimateLocked=false;}case"monitor"->c.performanceMonitor=!c.performanceMonitor;default-> {return;}}c.maxFpsPreset=false;c.competitiveMode=false;if(!k.equals("performance"))c.ultimateLocked=false;c.markDirty();rebuildWidgets();}
    private void target(){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked)return;c.dynamicTargetFps=c.dynamicTargetFps>=240?60:c.dynamicTargetFps+30;c.maxFpsPreset=false;c.competitiveMode=false;c.markDirty();rebuildWidgets();}
    private void entityDistance(){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked)return;c.maxEntityDistance=c.maxEntityDistance>=128?32:c.maxEntityDistance+16;c.maxFpsPreset=false;c.competitiveMode=false;c.markDirty();rebuildWidgets();}
    private void renderDistance(){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked)return;c.maxRenderDistance=c.maxRenderDistance>=12?4:c.maxRenderDistance+2;c.maxFpsPreset=false;c.competitiveMode=false;c.markDirty();rebuildWidgets();}
    private void particleBudget(){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked)return;c.particleLimitPercent=c.particleLimitPercent>=100?10:c.particleLimitPercent+10;c.maxFpsPreset=false;c.competitiveMode=false;c.markDirty();rebuildWidgets();}
    private void fpsLimit(){VoidBoostConfig c=VoidBoostConfig.get();if(c.ultimateLocked)return;int[] v={60,120,144,165,240,360,1000};int n=60;for(int x:v)if(x>c.targetFps){n=x;break;}c.targetFps=n;c.maxFpsPreset=false;c.competitiveMode=false;c.markDirty();rebuildWidgets();}
    private static String state(String k){VoidBoostConfig c=VoidBoostConfig.get();return switch(k){case"particles"->c.disableParticles?"MINIMAL":c.reducedParticles?"REDUCED":"ALL";case"dynamic"->c.dynamicRenderDistance?"ON":"OFF";case"entities"->c.entityRenderOptimization?"ON":"OFF";case"shadows"->c.entityShadows?"ON":"OFF";case"weather"->c.weatherEffects?"ON":"OFF";case"clouds"->c.cloudOptimization?"ON":"OFF";case"animations"->c.animationOptimization?"ON":"OFF";case"fog"->c.fogOptimization?"ON":"OFF";case"vignette"->c.vignetteOptimization?"ON":"OFF";case"ao"->c.ambientOcclusionOptimization?"ON":"OFF";case"mipmap"->c.mipmapOptimization?"ON":"OFF";case"biome"->c.biomeBlendOptimization?"ON":"OFF";case"vsync"->c.vsyncOptimization?"ON":"OFF";case"viewbob"->c.viewBobOptimization?"ON":"OFF";case"performance"->c.performanceMode?"ON":"OFF";case"monitor"->c.performanceMonitor?"ON":"OFF";default->"OFF";};}
    private static String mode(){if(preset("ultimate"))return"ULTIMATE FPS";if(preset("competitive"))return"COMPETITIVE";if(preset("max"))return"MAX FPS";if(preset("balanced"))return"BALANCED";return"CUSTOM";}
    private static boolean preset(String n){VoidBoostConfig c=VoidBoostConfig.get();return switch(n){case"ultimate"->c.ultimateLocked;case"competitive"->c.competitiveMode&&!c.maxFpsPreset&&!c.ultimateLocked;case"max"->c.maxFpsPreset&&!c.competitiveMode&&!c.ultimateLocked;case"balanced"->!c.competitiveMode&&!c.maxFpsPreset&&!c.ultimateLocked&&c.performanceMode&&!c.disableParticles&&c.reducedParticles&&!c.entityShadows&&!c.weatherEffects&&c.animationOptimization&&c.fogOptimization&&c.entityRenderOptimization&&c.dynamicRenderDistance&&c.cloudOptimization&&c.vignetteOptimization&&c.ambientOcclusionOptimization&&c.mipmapOptimization&&c.biomeBlendOptimization&&!c.viewBobOptimization&&c.vsyncOptimization&&c.dynamicTargetFps==120&&c.maxEntityDistance==56&&c.maxRenderDistance==10;case"custom"->!preset("balanced")&&!c.competitiveMode&&!c.maxFpsPreset&&!c.ultimateLocked;default->false;};}
    @Override public void render(GuiGraphics g,int mx,int my,float delta){int sx=26,st=24,sr=width-26,sb=height-24,side=180,cx=202,clip=sb-48;g.fill(0,0,width,height,BG);g.fill(sx,st,sr,sb,SHELL);g.fill(sx,st,side,sb,SIDE);g.fill(sx,st,sr,st+2,ACCENT);g.fill(side,st+2,side+1,sb,BORDER);g.fill(sx+14,40,sx+48,74,SOFT);g.fill(sx+14,40,sx+17,74,ACCENT);g.drawString(font,Component.literal("V"),sx+25,48,TEXT,false);g.drawString(font,Component.literal("VoidBoost"),sx+60,41,TEXT,false);g.drawString(font,Component.literal("PERFORMANCE SUITE"),sx+60,56,MUTED,false);g.drawString(font,Component.literal("CONTROL CENTER"),sx+12,94,MUTED,false);g.drawString(font,Component.literal("Made by VoidFlame"),sx+12,sb-38,MUTED,false);g.drawString(font,Component.literal("LIGHTWEIGHT ENGINE"),sx+12,sb-25,MUTED,false);String title=switch(page){case 0->"General";case 1->"Visual";case 2->"Performance";default->"Advanced";};String sub=switch(page){case 0->"Profiles & adaptive rendering";case 1->"Visual workload controls";case 2->"Frame-time optimization";default->"Fine-grained low-end tuning";};g.drawString(font,Component.literal(title),cx,42,TEXT,false);g.drawString(font,Component.literal(sub),cx,57,MUTED,false);g.enableScissor(0,82,width,clip);super.render(g,mx,my,delta);g.disableScissor();int bottom=sb-50,track=Math.max(1,bottom-82),thumb=Math.max(28,track*track/(track+maxScroll())),ty=82+(int)((track-thumb)*(scroll/Math.max(1,maxScroll())));g.fill(sr-26,82,sr-23,bottom,BORDER);g.fill(sr-26,ty,sr-23,ty+thumb,ACCENT);g.fill(cx,sb-49,sr-12,sb-48,BORDER);g.drawString(font,Component.literal("VOIDBOOST • FABRIC • MINECRAFT 1.21.11"),cx,sb-25,MUTED,false);}
    private static final class PremiumButton extends AbstractWidget{
        private final String title,value,description;private final Runnable action;private final boolean selected,compact;
        PremiumButton(int x,int y,int w,int h,String t,String v,String d,Runnable a,boolean s,boolean c){super(x,y,w,h,Component.literal(t));title=t;value=v;description=d;action=a;selected=s;compact=c;}
        @Override protected void renderWidget(GuiGraphics g,int mx,int my,float delta){boolean h=isHovered();int f=selected?SEL:h?HOVER:CARD,e=selected?ACCENT:h?0xFF3A4355:BORDER;g.fill(getX(),getY(),getX()+width,getY()+height,f);g.fill(getX(),getY(),getX()+3,getY()+height,e);if(selected)g.fill(getX()+3,getY(),getX()+width,getY()+2,ACCENT);int ty=getY()+(compact?11:12);g.drawString(Minecraft.getInstance().font,Component.literal(title),getX()+16,ty,h||selected?TEXT:0xFFE7EAF0,false);if(!description.isEmpty()&&!compact)g.drawString(Minecraft.getInstance().font,Component.literal(description),getX()+16,ty+17,MUTED,false);if(!value.isEmpty()){int x=getX()+width-Minecraft.getInstance().font.width(value)-16;g.drawString(Minecraft.getInstance().font,Component.literal(value),x,getY()+13,selected?ACCENT:value.equals("OFF")?BAD:GOOD,false);}}
        @Override public void onClick(MouseButtonEvent event,boolean isDoubleClick){action.run();}
        @Override protected void updateWidgetNarration(NarrationElementOutput output){defaultButtonNarrationText(output);}
    }
}
